[2024-02-23T15:40:04.124+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:40:04.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:40:04.173+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:40:04.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:40:04.408+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:40:04.380+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:40:04.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:40:04.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.513 seconds
[2024-02-23T15:41:00.962+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:00.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:41:01.022+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:41:01.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:01.263+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:41:01.233+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:41:01.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:01.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.812 seconds
[2024-02-23T15:41:59.571+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:59.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:41:59.623+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:41:59.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:59.714+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:41:59.703+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:41:59.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:41:59.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.373 seconds
[2024-02-23T15:42:30.464+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:30.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:42:30.483+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:42:30.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:30.565+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:42:30.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:42:30.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:30.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.203 seconds
[2024-02-23T15:42:59.406+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:59.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:42:59.469+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:42:59.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:59.615+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:42:59.599+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:42:59.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:42:59.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.520 seconds
[2024-02-23T15:43:30.665+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:43:30.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:43:30.714+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:43:30.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:43:30.823+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:43:30.807+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:43:30.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:43:30.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.344 seconds
[2024-02-23T15:44:03.712+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:03.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:44:03.732+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:03.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:03.789+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:03.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:44:03.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:03.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.178 seconds
[2024-02-23T15:44:34.510+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:34.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:44:34.538+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:34.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:34.608+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:34.597+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:44:34.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:34.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.203 seconds
[2024-02-23T15:44:43.916+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:43.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:44:43.959+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:43.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:44.131+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:44:44.102+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:44:44.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:44:44.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.424 seconds
[2024-02-23T15:45:14.399+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:14.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:45:14.414+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:45:14.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:14.462+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:45:14.453+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:45:14.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:14.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.150 seconds
[2024-02-23T15:45:44.882+0000] {processor.py:161} INFO - Started process (PID=670) to work on /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:44.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/assignment_12.py for tasks to queue
[2024-02-23T15:45:44.901+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:45:44.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:44.963+0000] {logging_mixin.py:188} INFO - [2024-02-23T15:45:44.950+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/assignment_12.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/assignment_12.py", line 22, in <module>
    export_to_sheets_task = SQLToGoogleSheetsOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 423, in apply_defaults
    raise AirflowException(f"missing keyword arguments {display}")
airflow.exceptions.AirflowException: missing keyword arguments 'spreadsheet_id', 'sql_conn_id'
[2024-02-23T15:45:44.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/assignment_12.py
[2024-02-23T15:45:45.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/assignment_12.py took 0.175 seconds
